cmake_version:
  - ">=3.20.1,<3.23"

cuda_python_version:
  - ">=11.5,<12.0"

cupy_version:
  - ">=9.5.0,<11.0.0a0"

cython_version:
  - ">=0.29,<0.30"

dask_version:
  - ">=2022.03.0"

distributed_version:
  - ">=2022.03.0"

dlpack_version:
  - ">=0.5,<0.6.0a0"

fastavro_version:
  - ">=0.22.0"

fsspec_version:
  - ">=0.6.0"

numba_version:
  - ">=0.54"

nvtx_version:
  - ">=0.2.1"

pandas_version:
  - ">=1.0,<1.4.0dev0"

pyarrow_version:
  - "7.0.0 *cuda"

python_confluent_kafka_version:
  - ">=1.7.0,<1.8.0a0"
